// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5op8vmTcVCpKgCCeZ0Ir6hPmujhVTOE0',
    appId: '1:938292604093:web:34850d2421b0f5a79f9bd4',
    messagingSenderId: '938292604093',
    projectId: 'booking-hotel-fe6da',
    authDomain: 'booking-hotel-fe6da.firebaseapp.com',
    storageBucket: 'booking-hotel-fe6da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgUp3UFW22b9-qcedwvv-aj5JvVHCoD4',
    appId: '1:938292604093:android:58977d918cdfa22c9f9bd4',
    messagingSenderId: '938292604093',
    projectId: 'booking-hotel-fe6da',
    storageBucket: 'booking-hotel-fe6da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqm021J-cO0l44dELnV6WVsVYYjHZ6tk',
    appId: '1:938292604093:ios:08bb5d5eec2e6ec89f9bd4',
    messagingSenderId: '938292604093',
    projectId: 'booking-hotel-fe6da',
    storageBucket: 'booking-hotel-fe6da.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqm021J-cO0l44dELnV6WVsVYYjHZ6tk',
    appId: '1:938292604093:ios:08bb5d5eec2e6ec89f9bd4',
    messagingSenderId: '938292604093',
    projectId: 'booking-hotel-fe6da',
    storageBucket: 'booking-hotel-fe6da.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5op8vmTcVCpKgCCeZ0Ir6hPmujhVTOE0',
    appId: '1:938292604093:web:69d61cb2507db4579f9bd4',
    messagingSenderId: '938292604093',
    projectId: 'booking-hotel-fe6da',
    authDomain: 'booking-hotel-fe6da.firebaseapp.com',
    storageBucket: 'booking-hotel-fe6da.firebasestorage.app',
  );
}
